language: java
sudo: false
jdk:
  - openjdk12
cache:
  directories:
    - "~/.m2/repository"
branches:
  only:
    - master
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B