matrix:
  include:
    - language: java
      sudo: false
      jdk: openjdk12
      cache:
        directories:
          - "~/.m2/repository"
      branches:
        only:
          - master
      install: mvn -f immunohelper-support/pom.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script: mvn -f immunohelper-support/pom.xml test -B

notifications:
  email:
    - nbento.neves@gmail.com